# Generated by Django 5.2.3 on 2025-06-15 15:10

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_doctor_patient_patientdoctormapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientdoctormapping',
            name='assigned_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2025, 6, 15, 20, 40, 23, 726490)),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='doctor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='patient_mappings', to='core.doctor'),
        ),
        migrations.AlterField(
            model_name='patientdoctormapping',
            name='patient',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='doctor_mappings', to='core.patient'),
        ),
    ]
